/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.exoplayer;

import android.app.Activity;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiUIView;

@Kroll.proxy(creatableInModule = TiExoPlayerModule.class)
public class ExoPlayerProxy extends TiViewProxy {

    public ExoPlayerProxy() {
        super();
    }

    @Override
    public TiUIView createView(Activity activity) {
        TiUIView view = new ExoPlayerView(this);
        view.getLayoutParams().autoFillsHeight = true;
        view.getLayoutParams().autoFillsWidth = true;
        return view;
    }

    protected ExoPlayerView getView() {
        return (ExoPlayerView) getOrCreateView();
    }

    @Override
    public void handleCreationDict(KrollDict options) {
        super.handleCreationDict(options);
        // All initialization is handled inside ExoPlayerView constructor
        // reading from proxy.getProperty() to keep a single source of truth
    }

    // ─── url ──────────────────────────────────────────────────────────────────

    @Kroll.getProperty
    public String getUrl() {
        return getView().mediaUrl;
    }

    @Kroll.setProperty
    public void setUrl(String url) {
        getView().setMediaItem(url);
    }

    // ─── playing (read-only) ──────────────────────────────────────────────────

    @Kroll.getProperty
    public boolean getPlaying() {
        return getView().isPlaying;
    }

    // ─── scalingMode ─────────────────────────────────────────────────────────

    @Kroll.getProperty
    public int getScalingMode() {
        return getView().getScalingMode();
    }

    @Kroll.setProperty
    public void setScalingMode(int mode) {
        getView().setScalingMode(mode);
    }

    // ─── volume ───────────────────────────────────────────────────────────────

    @Kroll.getProperty
    public float getVolume() {
        return getView().getVolume();
    }

    @Kroll.setProperty
    public void setVolume(float vol) {
        getView().setVolume(vol);
    }

    // ─── muted ────────────────────────────────────────────────────────────────

    @Kroll.getProperty
    public boolean getMuted() {
        return getView().getMuted();
    }

    @Kroll.setProperty
    public void setMuted(boolean muted) {
        getView().setMuted(muted);
    }

    // ─── playbackSpeed ────────────────────────────────────────────────────────

    @Kroll.getProperty
    public float getPlaybackSpeed() {
        return getView().getPlaybackSpeed();
    }

    @Kroll.setProperty
    public void setPlaybackSpeed(float speed) {
        getView().setPlaybackSpeed(speed);
    }

    // ─── repeat ───────────────────────────────────────────────────────────────

    @Kroll.getProperty
    public boolean getRepeat() {
        return getView().getRepeat();
    }

    @Kroll.setProperty
    public void setRepeat(boolean repeat) {
        getView().setRepeat(repeat);
    }

    // ─── showControls ─────────────────────────────────────────────────────────

    @Kroll.getProperty
    public boolean getShowControls() {
        return getView().getShowControls();
    }

    @Kroll.setProperty
    public void setShowControls(boolean show) {
        getView().setShowControls(show);
    }

    // ─── audioOnly (read-only, set at creation) ───────────────────────────────

    @Kroll.getProperty
    public boolean getAudioOnly() {
        return false; // resolved inside view via proxy.getProperty("audioOnly")
    }

    // ─── currentPosition / duration (read-only) ───────────────────────────────

    @Kroll.getProperty
    public long getCurrentPosition() {
        return getView().currentPosition();
    }

    @Kroll.getProperty
    public long getDuration() {
        return getView().duration();
    }

    // ─── Methods ──────────────────────────────────────────────────────────────

    @Kroll.method
    public void play() {
        getView().play();
    }

    @Kroll.method
    public void pause() {
        getView().pause();
    }

    @Kroll.method
    public void stop() {
        getView().stop();
    }

    @Kroll.method
    public void release() {
        getView().release();
    }

    @Kroll.method
    public void seekTo(int value) {
        getView().seekTo(value);
    }
}