/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.exoplayer;

import android.content.res.Resources;
import android.view.LayoutInflater;

import com.google.android.exoplayer2.ExoPlayer;
import com.google.android.exoplayer2.MediaItem;
import com.google.android.exoplayer2.MediaMetadata;
import com.google.android.exoplayer2.Player;
import com.google.android.exoplayer2.ui.StyledPlayerView;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.view.TiUIView;

public class ExoPlayerView extends TiUIView implements Player.Listener {
    private static final String LCAT = "ExoPlayerProxy";
    ExoPlayer player = null;
    String mediaUrl = "";
    Boolean isPlaying = false;
    Boolean shouldPrepare = false;

    public ExoPlayerView(TiViewProxy proxy) {
        super(proxy);

        String pkgName = proxy.getActivity().getPackageName();
        Resources res = proxy.getActivity().getResources();
        int resId_viewHolder;
        if (TiConvert.toBoolean(proxy.getProperty("audioOnly"), false)) {
            resId_viewHolder = res.getIdentifier("audioplayer_view", "layout", pkgName);
        } else {
            resId_viewHolder = res.getIdentifier("player_view", "layout", pkgName);
        }
        LayoutInflater inflater = LayoutInflater.from(proxy.getActivity());
        StyledPlayerView viewWrapper = (StyledPlayerView) inflater.inflate(resId_viewHolder, null);
        setNativeView(viewWrapper);
        player = new ExoPlayer.Builder(TiApplication.getAppCurrentActivity()).build();
        viewWrapper.setPlayer(player);

        if (!mediaUrl.equals("")) {
            setMediaItem(mediaUrl);
        }

        player.addListener(this);
    }

    @Override
    public void onMediaMetadataChanged(MediaMetadata mediaMetadata) {
        Player.Listener.super.onMediaMetadataChanged(mediaMetadata);
        if (mediaMetadata != null) {
            KrollDict kd = new KrollDict();

            if (mediaMetadata.artist != null) kd.put("album", mediaMetadata.artist);
            if (mediaMetadata.title != null) kd.put("title", mediaMetadata.title);
            if (mediaMetadata.albumTitle != null) kd.put("albumTitle", mediaMetadata.albumTitle);
            if (mediaMetadata.albumArtist != null) kd.put("albumArtist", mediaMetadata.albumArtist);
            if (mediaMetadata.artworkUri != null)
                kd.put("artworkUrl", mediaMetadata.artworkUri.toString());
            /*if (mediaMetadata.artworkData != null) {
                kd.put("artwork", TiConvert.toBlob(mediaMetadata.artworkData));
            }*/

            fireEvent("metaData", kd);
        }
    }

    @Override
    public void onPlaybackStateChanged(int playbackState) {
        Player.Listener.super.onPlaybackStateChanged(playbackState);
        KrollDict kd = new KrollDict();
        if (playbackState == Player.STATE_BUFFERING) {
            kd.put("state", TiExoPlayerModule.STATE_BUFFERING);
        } else if (playbackState == Player.STATE_IDLE) {
            kd.put("state", TiExoPlayerModule.STATE_IDLE);
        } else if (playbackState == Player.STATE_READY) {
            kd.put("state", TiExoPlayerModule.STATE_READY);
        } else if (playbackState == Player.STATE_ENDED) {
            kd.put("state", TiExoPlayerModule.STATE_ENDED);
        }
        fireEvent("playerState", kd);
    }

    @Override
    public void onEvents(Player player, Player.Events events) {
        Player.Listener.super.onEvents(player, events);
    }

    @Override
    public void onIsPlayingChanged(boolean isPlaying) {
        Player.Listener.super.onIsPlayingChanged(isPlaying);
        KrollDict kd = new KrollDict();
        kd.put("state", TiExoPlayerModule.STATE_PLAYING);
        this.isPlaying = isPlaying;
        fireEvent("playerState", kd);
    }

    @Override
    public void onPositionDiscontinuity(Player.PositionInfo oldPosition, Player.PositionInfo newPosition, int reason) {
        Player.Listener.super.onPositionDiscontinuity(oldPosition, newPosition, reason);
        KrollDict kd = new KrollDict();
        kd.put("oldPosition", oldPosition.positionMs);
        kd.put("position", newPosition.positionMs);
        fireEvent("seek", kd);
    }

    @Override
    public void processProperties(KrollDict d) {
        super.processProperties(d);
    }

    public void setMediaItem(String url) {
        mediaUrl = url;
        if (player != null) {
            MediaItem mediaItem = MediaItem.fromUri(mediaUrl);
            player.setMediaItem(mediaItem);
            player.prepare();
            shouldPrepare = false;
        }
    }

    public void play() {
        if (shouldPrepare) {
            player.prepare();
        }
        player.play();
    }

    public void stop() {
        player.stop();
        shouldPrepare = true;
    }

    public void pause() {
        player.pause();
    }

    public void release() {
        player.release();
    }

    public void seekTo(int value) {
        player.seekTo(value);
    }
}
