/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.exoplayer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "TiExoplayer", id = "ti.exoplayer")
public class TiExoPlayerModule extends KrollModule {
    public TiExoPlayerModule() {
        super();
    }

    // Playback states
    @Kroll.constant static final int STATE_IDLE = 1;
    @Kroll.constant static final int STATE_BUFFERING = 2;
    @Kroll.constant static final int STATE_READY = 3;
    @Kroll.constant static final int STATE_ENDED = 4;
    @Kroll.constant static final int STATE_PLAYING = 5;

    // Scaling modes
    @Kroll.constant static final int SCALING_MODE_FIT = 0;   // RESIZE_MODE_FIT
    @Kroll.constant static final int SCALING_MODE_FILL = 3;  // RESIZE_MODE_FILL (stretch)
    @Kroll.constant static final int SCALING_MODE_CROP = 4;  // RESIZE_MODE_ZOOM (crop)

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }
}
